import React, {useEffect, useState} from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, NavLink, Route, Routes } from 'react-router-dom'
import { Activity, Archive, Database, HardDrive, Play, Plus, RotateCcw, Settings, ShieldCheck } from 'lucide-react'
import { api, Repository, Job } from './api'
import './styles.css'

const statusClass=(s:string)=>`pill ${s}`

function Layout(){
 const nav=[['/',Activity,'Overview'],['/repositories',Database,'Repositories'],['/backups',Play,'Backups'],['/archives',Archive,'Archives'],['/restore',RotateCcw,'Restore']]
 return <div className="shell"><aside><div className="brand"><div className="brandmark">B</div><div><b>Borg Manager</b><span>Backup control</span></div></div><nav>{nav.map(([to,Icon,label]:any)=><NavLink key={to} to={to} end={to==='/' }><Icon size={18}/>{label}</NavLink>)}</nav><div className="sidebottom"><ShieldCheck size={18}/> Local-first & self-hosted</div></aside><main><header><div><span className="eyebrow">BACKUP OPERATIONS</span><h1>Keep every restore within reach.</h1></div><div className="badge">BorgBackup</div></header><Routes><Route path="/" element={<Dashboard/>}/><Route path="/repositories" element={<Repositories/>}/><Route path="/backups" element={<Backups/>}/><Route path="/archives" element={<Archives/>}/><Route path="/restore" element={<Restore/>}/></Routes></main></div>
}

function Dashboard(){ const [data,setData]=useState<any>(null); useEffect(()=>{api.get('/dashboard').then(setData)},[]); if(!data)return <Card>Loading…</Card>; return <><div className="grid3"><Metric label="Repositories" value={data.repository_count} icon={<Database/>}/><Metric label="Recent successes" value={data.successful_recent} icon={<ShieldCheck/>}/><Metric label="Recent failures" value={data.failed_recent} icon={<Activity/>}/></div><section className="section"><div className="sectionTitle"><div><span className="eyebrow">ACTIVITY</span><h2>Recent backup jobs</h2></div></div><Card>{data.recent_jobs.length? <table><thead><tr><th>Archive</th><th>Status</th><th>Started</th></tr></thead><tbody>{data.recent_jobs.map((j:Job)=><tr key={j.id}><td>{j.archive_name}</td><td><span className={statusClass(j.status)}>{j.status}</span></td><td>{j.started_at?new Date(j.started_at).toLocaleString():'—'}</td></tr>)}</tbody></table>:<Empty text="No backup jobs yet."/>}</Card></section></> }
function Metric({label,value,icon}:{label:string,value:any,icon:any}){return <div className="metric"><div className="metricIcon">{icon}</div><span>{label}</span><strong>{value}</strong></div>}
function Card({children}:{children:React.ReactNode}){return <div className="card">{children}</div>}
function Empty({text}:{text:string}){return <div className="empty"><HardDrive size={28}/><b>{text}</b><span>Your backup workspace is ready.</span></div>}

function Repositories(){ const [repos,setRepos]=useState<Repository[]>([]); const [form,setForm]=useState({name:'',location:'',passphrase:''}); const load=()=>api.get<Repository[]>('/repositories').then(setRepos); useEffect(load,[]); async function add(e:React.FormEvent){e.preventDefault();await api.post('/repositories',form);setForm({name:'',location:'',passphrase:''});load()} return <section className="section"><div className="sectionTitle"><div><span className="eyebrow">STORAGE</span><h2>Repositories</h2></div></div><div className="split"><Card><form onSubmit={add}><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="NAS archive" required/></label><label>Repository location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="/repos/main or ssh://user@host/./repo" required/></label><label>Passphrase<input type="password" value={form.passphrase} onChange={e=>setForm({...form,passphrase:e.target.value})} placeholder="Optional"/></label><button><Plus size={16}/>Add repository</button></form></Card><Card>{repos.length?<div className="repoList">{repos.map(r=><div className="repo" key={r.id}><div className="repoIcon"><Database/></div><div><b>{r.name}</b><code>{r.location}</code></div><button className="ghost" onClick={async()=>{await api.del('/repositories/'+r.id);load()}}>Delete</button></div>)}</div>:<Empty text="No repositories configured."/>}</Card></div></section>}

function Backups(){ const [repos,setRepos]=useState<Repository[]>([]); const [jobs,setJobs]=useState<Job[]>([]); const [repo,setRepo]=useState(''); const [sources,setSources]=useState('/sources'); const [archive,setArchive]=useState(''); const load=()=>{api.get<Repository[]>('/repositories').then(r=>{setRepos(r);if(!repo&&r[0])setRepo(String(r[0].id))});api.get<Job[]>('/jobs').then(setJobs)}; useEffect(()=>{load();const t=setInterval(load,1500);return()=>clearInterval(t)},[]); async function run(e:React.FormEvent){e.preventDefault();await api.post('/backups',{repository_id:Number(repo),sources:sources.split(',').map(x=>x.trim()).filter(Boolean),archive_name:archive||null,compression:'zstd,3',excludes:[]});setArchive('');load()} return <section className="section"><div className="sectionTitle"><div><span className="eyebrow">EXECUTION</span><h2>Backups</h2></div></div><div className="split"><Card><form onSubmit={run}><label>Repository<select value={repo} onChange={e=>setRepo(e.target.value)}>{repos.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Source paths<input value={sources} onChange={e=>setSources(e.target.value)} placeholder="/sources/home, /sources/photos"/></label><label>Archive name<input value={archive} onChange={e=>setArchive(e.target.value)} placeholder="Generated automatically"/></label><button disabled={!repo}><Play size={16}/>Run backup</button></form></Card><Card>{jobs.length?<div className="jobList">{jobs.slice(0,12).map(j=><div className="job" key={j.id}><div><b>{j.archive_name}</b><small>Repository #{j.repository_id}</small></div><span className={statusClass(j.status)}>{j.status}</span></div>)}</div>:<Empty text="No jobs yet."/>}</Card></div></section>}

function Archives(){ const [repos,setRepos]=useState<Repository[]>([]); const [repo,setRepo]=useState(''); const [archives,setArchives]=useState<any[]>([]); const [selected,setSelected]=useState(''); const [files,setFiles]=useState<any[]>([]); useEffect(()=>{api.get<Repository[]>('/repositories').then(r=>{setRepos(r);if(r[0])setRepo(String(r[0].id))})},[]); async function load(){if(!repo)return;setArchives(await api.get(`/repositories/${repo}/archives`));setFiles([])} async function browse(name:string){setSelected(name);setFiles(await api.get(`/repositories/${repo}/archives/${encodeURIComponent(name)}/files`))} return <section className="section"><div className="sectionTitle"><div><span className="eyebrow">HISTORY</span><h2>Archives</h2></div><div className="inline"><select value={repo} onChange={e=>setRepo(e.target.value)}>{repos.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><button onClick={load}>Load archives</button></div></div><div className="split"><Card>{archives.length?archives.map(a=><button className={`archiveRow ${selected===a.name?'selected':''}`} onClick={()=>browse(a.name)} key={a.name}><Archive size={17}/><span><b>{a.name}</b><small>{a.time||''}</small></span></button>):<Empty text="Load a repository to browse archives."/>}</Card><Card>{files.length?<table><thead><tr><th>Path</th><th>Size</th></tr></thead><tbody>{files.map((f:any,i)=><tr key={i}><td className="path">{f.path}</td><td>{typeof f.size==='number'?formatBytes(f.size):'—'}</td></tr>)}</tbody></table>:<Empty text="Select an archive to browse files."/>}</Card></div></section>}
function formatBytes(n:number){if(n<1024)return n+' B';const u=['KB','MB','GB','TB'];let i=-1;do{n/=1024;i++}while(n>=1024&&i<u.length-1);return n.toFixed(1)+' '+u[i]}

function Restore(){ const [repos,setRepos]=useState<Repository[]>([]); const [repo,setRepo]=useState(''); const [archive,setArchive]=useState(''); const [paths,setPaths]=useState(''); const [target,setTarget]=useState('restored'); const [msg,setMsg]=useState(''); useEffect(()=>{api.get<Repository[]>('/repositories').then(r=>{setRepos(r);if(r[0])setRepo(String(r[0].id))})},[]); async function restore(e:React.FormEvent){e.preventDefault();setMsg('Restoring…');try{const r:any=await api.post('/restore',{repository_id:Number(repo),archive,paths:paths?paths.split(',').map(x=>x.trim()):[],target});setMsg(`Restore complete: ${r.target}`)}catch(e:any){setMsg(e.message)}} return <section className="section"><div className="sectionTitle"><div><span className="eyebrow">RECOVERY</span><h2>Restore</h2></div></div><Card><form className="wideForm" onSubmit={restore}><label>Repository<select value={repo} onChange={e=>setRepo(e.target.value)}>{repos.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label><label>Archive<input value={archive} onChange={e=>setArchive(e.target.value)} required placeholder="backup-2026-09-01_10-00-00"/></label><label>Paths<input value={paths} onChange={e=>setPaths(e.target.value)} placeholder="Optional; comma-separated. Empty = full archive"/></label><label>Target inside /restore<input value={target} onChange={e=>setTarget(e.target.value)} required/></label><button><RotateCcw size={16}/>Restore archive</button>{msg&&<div className="notice">{msg}</div>}</form></Card></section>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><Layout/></BrowserRouter></React.StrictMode>)
